/**
 * continuum_attest — H (the human) signs the ACCEPT. The P9 boundary, enforced mechanically.
 *
 * This is the only tool that can mint the final acceptance — the liability transfer and the
 * establishment of human IP ownership. Because trust cannot be generated by the agent (P9),
 * this tool is fundamentally unreachable by any LLM caller:
 *
 *   1. The submitted `decision` entry must carry a signature that verifies against a
 *      registered key (the ledger rejects forged/unregistered signatures), AND
 *   2. that key's role MUST be 'human'. An entry signed by an executor/validator key is
 *      refused here BEFORE it ever reaches the ledger.
 *
 * There is NO MCP tool to register a human key (identities are set up out-of-band, locally),
 * so an LLM can neither forge H's signature nor mint a human identity of its own. Only when
 * A + V + T are already green does H's accept flip the verdict to PROVEN → DONE opens.
 *
 * IP by Riaan Kleynhans — Human in the Loop — Copyright Riaan Kleynhans
 */
import { todoTaskRef } from '@number7even/continuum-core';
import type { LedgerEntry } from '@number7even/continuum-core';
import type { ToolDefinition, ToolHandler } from '../tool-types.js';

export const attestTool: ToolDefinition = {
  name: 'continuum_attest',
  description:
    'H (the human) signs the final ACCEPT — the P9 leap that transfers liability and establishes ' +
    'human IP ownership. Pass todoId and a signed `decision` LedgerEntry (decision:"accept", ' +
    'role:"human"). MECHANICALLY REQUIRES a registered HUMAN key: an LLM cannot produce a valid ' +
    'human signature and there is no tool to register one, so this tool cannot be reached by an ' +
    'agent. Only finalizes PROVEN when A (claim) + V (validation) + T (test exit 0) are present.',
  inputSchema: {
    type: 'object',
    properties: {
      todoId: { type: 'string' },
      entry: { type: 'object', description: 'A signed LedgerEntry of kind "decision" (role "human").' },
    },
    required: ['todoId', 'entry'],
  },
};

export const handleAttest: ToolHandler = async (args, storage) => {
  const { todoId, entry } = (args ?? {}) as { todoId?: string; entry?: LedgerEntry };
  if (!todoId || !entry) throw new Error('todoId and a signed entry are required');
  if (entry.kind !== 'decision') throw new Error(`continuum_attest expects a "decision" entry, got "${entry.kind}"`);

  // P9 boundary — the key that signs an acceptance MUST resolve to a registered human identity.
  const signer = storage.listIdentities().find(i => i.keyId === entry.by);
  if (!signer || signer.role !== 'human') {
    throw new Error(
      `P9 violation: continuum_attest requires a registered HUMAN key. Key "${entry.by}" is ` +
      `${signer ? `role "${signer.role}"` : 'unregistered'} — an agent cannot mint the human leap.`,
    );
  }

  const taskRef = todoTaskRef(todoId);
  const block = storage.submitLedgerEntry(taskRef, entry);
  return {
    content: [{ type: 'text', text: JSON.stringify({ taskRef, verdict: block.verdict, blockHash: block.blockHash, finalized: block.verdict === 'PROVEN' }, null, 2) }],
  };
};
